import type { ColumnInfo } from '#/lib/pg/catalog-types'

export const OMIT = Symbol('OMIT')

export function isAutoGeneratedColumn(column: ColumnInfo): boolean {
  if (!column.defaultValue) {
    return false
  }

  return /nextval\s*\(|gen_random_uuid\s*\(|uuid_generate_v4\s*\(|\bnow\s*\(\s*\)|CURRENT_TIMESTAMP/i.test(
    column.defaultValue,
  )
}

export function cellValueToInput(value: unknown): string {
  if (value === null || value === undefined) {
    return ''
  }

  if (typeof value === 'object') {
    if (value instanceof Date) {
      return value.toISOString()
    }

    return JSON.stringify(value)
  }

  return String(value)
}

export function parseCellInput(
  raw: string,
  column: ColumnInfo,
  mode: 'insert' | 'update',
): unknown | typeof OMIT {
  const trimmed = raw.trim()

  if (trimmed === '' || trimmed.toUpperCase() === 'NULL') {
    if (trimmed.toUpperCase() === 'NULL') {
      if (!column.isNullable) {
        throw new Error(`${column.name} cannot be null`)
      }

      return null
    }

    if (mode === 'insert') {
      if (isAutoGeneratedColumn(column)) {
        return OMIT
      }

      if (column.defaultValue) {
        return OMIT
      }

      if (column.isNullable) {
        return null
      }

      throw new Error(`${column.name} is required`)
    }

    if (column.isNullable) {
      return null
    }

    throw new Error(`${column.name} is required`)
  }

  return coerceValue(trimmed, column)
}

export function parseRowValues(
  inputs: Record<string, string>,
  columns: ColumnInfo[],
  mode: 'insert' | 'update',
): Record<string, unknown> {
  const result: Record<string, unknown> = {}

  for (const column of columns) {
    if (mode === 'update' && column.isPrimaryKey) {
      continue
    }

    if (!(column.name in inputs)) {
      continue
    }

    const parsed = parseCellInput(inputs[column.name] ?? '', column, mode)

    if (parsed === OMIT) {
      continue
    }

    result[column.name] = parsed
  }

  return result
}

function coerceValue(raw: string, column: ColumnInfo): unknown {
  const type = column.dataType.toLowerCase()

  if (type === 'boolean') {
    const normalized = raw.toLowerCase()
    if (['true', 't', '1', 'yes', 'y'].includes(normalized)) {
      return true
    }
    if (['false', 'f', '0', 'no', 'n'].includes(normalized)) {
      return false
    }

    throw new Error(`${column.name}: expected a boolean (true/false)`)
  }

  if (
    type === 'smallint' ||
    type === 'integer' ||
    type === 'bigint' ||
    type === 'oid'
  ) {
    const value = Number(raw)
    if (!Number.isInteger(value)) {
      throw new Error(`${column.name}: expected an integer`)
    }
    return value
  }

  if (
    type === 'numeric' ||
    type === 'real' ||
    type === 'double precision' ||
    type === 'decimal'
  ) {
    const value = Number(raw)
    if (Number.isNaN(value)) {
      throw new Error(`${column.name}: expected a number`)
    }
    return value
  }

  if (type === 'json' || type === 'jsonb') {
    try {
      return JSON.parse(raw)
    } catch {
      throw new Error(`${column.name}: invalid JSON`)
    }
  }

  return raw
}

export function assertAllowedColumns(
  values: Record<string, unknown>,
  allowedColumns: string[],
) {
  for (const column of Object.keys(values)) {
    if (!allowedColumns.includes(column)) {
      throw new Error(`Invalid column: ${column}`)
    }
  }
}
