import { describe, expect, it } from 'vitest'

import type { ColumnInfo } from '#/lib/pg/catalog-types'
import {
  OMIT,
  cellValueToInput,
  isAutoGeneratedColumn,
  parseCellInput,
  parseRowValues,
} from '#/lib/pg/cell-values'

function column(overrides: Partial<ColumnInfo> = {}): ColumnInfo {
  return {
    name: 'id',
    dataType: 'text',
    isNullable: false,
    defaultValue: null,
    isPrimaryKey: false,
    isForeignKey: false,
    ...overrides,
  }
}

describe('isAutoGeneratedColumn', () => {
  it('detects serial defaults', () => {
    expect(
      isAutoGeneratedColumn(
        column({ defaultValue: "nextval('users_id_seq'::regclass)" }),
      ),
    ).toBe(true)
  })
})

describe('cellValueToInput', () => {
  it('formats null as empty string', () => {
    expect(cellValueToInput(null)).toBe('')
  })

  it('stringifies json values', () => {
    expect(cellValueToInput({ ok: true })).toBe('{"ok":true}')
  })
})

describe('parseCellInput', () => {
  it('omits empty serial columns on insert', () => {
    expect(
      parseCellInput(
        '',
        column({ defaultValue: "nextval('users_id_seq'::regclass)" }),
        'insert',
      ),
    ).toBe(OMIT)
  })

  it('parses booleans', () => {
    expect(parseCellInput('true', column({ dataType: 'boolean' }), 'update')).toBe(
      true,
    )
  })

  it('parses explicit null', () => {
    expect(
      parseCellInput('NULL', column({ isNullable: true }), 'update'),
    ).toBeNull()
  })
})

describe('parseRowValues', () => {
  it('skips primary key columns on update', () => {
    const values = parseRowValues(
      { id: '1', name: 'Ada' },
      [
        column({ name: 'id', isPrimaryKey: true }),
        column({ name: 'name', isNullable: true }),
      ],
      'update',
    )

    expect(values).toEqual({ name: 'Ada' })
  })
})
