import type { ColumnInfo } from '#/lib/pg/catalog-types'
import {
  getColumnFieldKind,
  isFieldValueNull,
} from '#/lib/pg/column-field'
import { isAutoGeneratedColumn } from '#/lib/pg/cell-values'

function pad(value: number) {
  return String(value).padStart(2, '0')
}

function formatDateLocal(value: Date) {
  return `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())}`
}

function formatTimeLocal(value: Date) {
  return `${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`
}

function formatDatetimeLocal(value: Date) {
  return `${formatDateLocal(value)}T${formatTimeLocal(value)}`
}

export function isUuidColumn(column: ColumnInfo) {
  return column.dataType.toLowerCase() === 'uuid'
}

export function supportsClientGeneration(
  column: ColumnInfo,
  mode: 'insert' | 'edit',
) {
  if (mode === 'edit' && column.isPrimaryKey) {
    return false
  }

  const kind = getColumnFieldKind(column)

  return isUuidColumn(column) || kind === 'date' || kind === 'time' || kind === 'datetime'
}

export function generateFieldValue(column: ColumnInfo) {
  const kind = getColumnFieldKind(column)
  const now = new Date()

  if (isUuidColumn(column)) {
    return crypto.randomUUID()
  }

  if (kind === 'date') {
    return formatDateLocal(now)
  }

  if (kind === 'time') {
    return formatTimeLocal(now)
  }

  if (kind === 'datetime') {
    return formatDatetimeLocal(now)
  }

  throw new Error(`Cannot generate value for ${column.name}`)
}

export function generateMissingFieldValues(
  values: Record<string, string>,
  columns: ColumnInfo[],
  mode: 'insert' | 'edit',
) {
  const next = { ...values }

  for (const column of columns) {
    if (!shouldGenerateMissingField(column, mode, next[column.name] ?? '')) {
      continue
    }

    next[column.name] = generateFieldValue(column)
  }

  return next
}

function shouldGenerateMissingField(
  column: ColumnInfo,
  mode: 'insert' | 'edit',
  value: string,
) {
  if (!supportsClientGeneration(column, mode)) {
    return false
  }

  if (!isFieldValueNull(value)) {
    return false
  }

  if (mode === 'insert' && isAutoGeneratedColumn(column)) {
    return false
  }

  return true
}

export function listGeneratableColumns(
  columns: ColumnInfo[],
  mode: 'insert' | 'edit',
) {
  return columns.filter((column) => supportsClientGeneration(column, mode))
}
