import { RelationField } from '#/components/browse/RelationField'
import { Input } from '#/components/ui/input'
import {
  Field,
  FieldActions,
  FieldGenerateAction,
  FieldHint,
  FieldLabel,
  FieldNullToggle,
  NativeSelect,
} from '#/components/ui/form-layout'
import { Textarea } from '#/components/ui/textarea'
import type { ColumnInfo, ColumnRelation, ForeignKeyInfo } from '#/lib/pg/catalog-types'
import {
  getColumnFieldKind,
  inputStepForKind,
  isExplicitNullValue,
} from '#/lib/pg/column-field'
import { isAutoGeneratedColumn } from '#/lib/pg/cell-values'
import { getColumnRelation, relationHintSuffix } from '#/lib/pg/foreign-keys'
import {
  generateFieldValue,
  supportsClientGeneration,
} from '#/lib/pg/generate-field-value'

type RowFieldProps = {
  column: ColumnInfo
  columns: ColumnInfo[]
  mode: 'insert' | 'edit'
  value: string
  readOnly?: boolean
  fieldId: string
  foreignKeys: ForeignKeyInfo[]
  relationValues: Record<string, string>
  connectionId: string
  database: string
  schema: string
  table: string
  onChange: (value: string) => void
  onRelationValuesChange: (values: Record<string, string>) => void
}

function columnHint(
  column: ColumnInfo,
  mode: 'insert' | 'edit',
  relation: ColumnRelation | null,
) {
  const parts = [column.dataType]

  if (relation) {
    parts.push(relationHintSuffix(relation))
  }

  if (column.isNullable) {
    parts.push('nullable')
  }

  if (column.isPrimaryKey) {
    parts.push('primary key')
  }

  if (mode === 'insert' && isAutoGeneratedColumn(column)) {
    parts.push('auto-generated')
  } else if (column.defaultValue) {
    parts.push(`default: ${column.defaultValue}`)
  }

  if (supportsClientGeneration(column, mode)) {
    parts.push('use Generate')
  }

  return parts.join(' · ')
}

export function RowField({
  column,
  columns,
  mode,
  value,
  readOnly = false,
  fieldId,
  foreignKeys,
  relationValues,
  connectionId,
  database,
  schema,
  table,
  onChange,
  onRelationValuesChange,
}: RowFieldProps) {
  const kind = getColumnFieldKind(column)
  const relation = getColumnRelation(column.name, columns, schema, foreignKeys)
  const isExplicitNull = isExplicitNullValue(value)
  const canSetNull = column.isNullable && !readOnly
  const canGenerate = supportsClientGeneration(column, mode) && !readOnly
  const inputDisabled = readOnly || isExplicitNull
  const monoClassName = 'field-mono'

  const renderControl = () => {
    if (relation && !readOnly) {
      return (
        <RelationField
          connectionId={connectionId}
          database={database}
          schema={schema}
          table={table}
          relation={relation}
          relationValues={relationValues}
          fieldId={fieldId}
          value={isExplicitNull ? '' : value}
          disabled={inputDisabled}
          onChange={onChange}
          onRelationValuesChange={onRelationValuesChange}
        />
      )
    }

    if (kind === 'boolean') {
      return (
        <NativeSelect
          id={fieldId}
          value={value}
          disabled={readOnly}
          className={monoClassName}
          onChange={(event) => onChange(event.target.value)}
        >
          {column.isNullable ? <option value="">NULL</option> : null}
          {!column.isNullable && value === '' ? (
            <option value="" disabled>
              Select...
            </option>
          ) : null}
          <option value="true">true</option>
          <option value="false">false</option>
        </NativeSelect>
      )
    }

    if (kind === 'json' || kind === 'text') {
      return (
        <Textarea
          id={fieldId}
          value={isExplicitNull ? '' : value}
          readOnly={inputDisabled}
          rows={kind === 'json' ? 5 : 3}
          placeholder={kind === 'json' ? '{\n  "key": "value"\n}' : undefined}
          className={monoClassName}
          onChange={(event) => onChange(event.target.value)}
        />
      )
    }

    if (kind === 'date') {
      return (
        <Input
          id={fieldId}
          type="date"
          value={isExplicitNull ? '' : value}
          readOnly={inputDisabled}
          className={monoClassName}
          onChange={(event) => onChange(event.target.value)}
        />
      )
    }

    if (kind === 'time') {
      return (
        <Input
          id={fieldId}
          type="time"
          step="1"
          value={isExplicitNull ? '' : value}
          readOnly={inputDisabled}
          className={monoClassName}
          onChange={(event) => onChange(event.target.value)}
        />
      )
    }

    if (kind === 'datetime') {
      return (
        <Input
          id={fieldId}
          type="datetime-local"
          step="1"
          value={isExplicitNull ? '' : value}
          readOnly={inputDisabled}
          className={monoClassName}
          onChange={(event) => onChange(event.target.value)}
        />
      )
    }

    if (kind === 'integer' || kind === 'number') {
      return (
        <Input
          id={fieldId}
          type="number"
          inputMode={kind === 'integer' ? 'numeric' : 'decimal'}
          step={inputStepForKind(kind)}
          value={isExplicitNull ? '' : value}
          readOnly={inputDisabled}
          className={monoClassName}
          onChange={(event) => onChange(event.target.value)}
        />
      )
    }

    return (
      <Input
        id={fieldId}
        type="text"
        value={isExplicitNull ? '' : value}
        readOnly={inputDisabled}
        placeholder={
          column.dataType.toLowerCase() === 'uuid'
            ? '00000000-0000-0000-0000-000000000000'
            : undefined
        }
        className={monoClassName}
        onChange={(event) => onChange(event.target.value)}
      />
    )
  }

  return (
    <Field>
      <div className="flex items-center justify-between gap-3">
        <FieldLabel htmlFor={fieldId}>{column.name}</FieldLabel>
        {canGenerate || canSetNull ? (
          <FieldActions>
            {canGenerate ? (
              <FieldGenerateAction
                disabled={isExplicitNull}
                onClick={() => onChange(generateFieldValue(column))}
              />
            ) : null}
            {canSetNull && kind !== 'boolean' ? (
              <FieldNullToggle
                checked={isExplicitNull}
                onCheckedChange={(checked) => onChange(checked ? 'NULL' : '')}
              />
            ) : null}
          </FieldActions>
        ) : null}
      </div>
      <FieldHint>{columnHint(column, mode, relation)}</FieldHint>
      {renderControl()}
    </Field>
  )
}
