/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionsNewRouteImport } from './routes/connections/new'
import { Route as ConnectConnectionIdRouteRouteImport } from './routes/connect/$connectionId/route'
import { Route as ConnectConnectionIdIndexRouteImport } from './routes/connect/$connectionId/index'
import { Route as ConnectionsConnectionIdEditRouteImport } from './routes/connections/$connectionId/edit'
import { Route as ConnectConnectionIdDatabaseSchemaTableIndexRouteImport } from './routes/connect/$connectionId/$database/$schema/$table/index'
import { Route as ConnectConnectionIdDatabaseSchemaTableStructureRouteImport } from './routes/connect/$connectionId/$database/$schema/$table/structure'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsNewRoute = ConnectionsNewRouteImport.update({
  id: '/connections/new',
  path: '/connections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectConnectionIdRouteRoute =
  ConnectConnectionIdRouteRouteImport.update({
    id: '/connect/$connectionId',
    path: '/connect/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectConnectionIdIndexRoute =
  ConnectConnectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectConnectionIdRouteRoute,
  } as any)
const ConnectionsConnectionIdEditRoute =
  ConnectionsConnectionIdEditRouteImport.update({
    id: '/connections/$connectionId/edit',
    path: '/connections/$connectionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectConnectionIdDatabaseSchemaTableIndexRoute =
  ConnectConnectionIdDatabaseSchemaTableIndexRouteImport.update({
    id: '/$database/$schema/$table/',
    path: '/$database/$schema/$table/',
    getParentRoute: () => ConnectConnectionIdRouteRoute,
  } as any)
const ConnectConnectionIdDatabaseSchemaTableStructureRoute =
  ConnectConnectionIdDatabaseSchemaTableStructureRouteImport.update({
    id: '/$database/$schema/$table/structure',
    path: '/$database/$schema/$table/structure',
    getParentRoute: () => ConnectConnectionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect/$connectionId': typeof ConnectConnectionIdRouteRouteWithChildren
  '/connections/new': typeof ConnectionsNewRoute
  '/connections/$connectionId/edit': typeof ConnectionsConnectionIdEditRoute
  '/connect/$connectionId/': typeof ConnectConnectionIdIndexRoute
  '/connect/$connectionId/$database/$schema/$table/structure': typeof ConnectConnectionIdDatabaseSchemaTableStructureRoute
  '/connect/$connectionId/$database/$schema/$table/': typeof ConnectConnectionIdDatabaseSchemaTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/connections/$connectionId/edit': typeof ConnectionsConnectionIdEditRoute
  '/connect/$connectionId': typeof ConnectConnectionIdIndexRoute
  '/connect/$connectionId/$database/$schema/$table/structure': typeof ConnectConnectionIdDatabaseSchemaTableStructureRoute
  '/connect/$connectionId/$database/$schema/$table': typeof ConnectConnectionIdDatabaseSchemaTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect/$connectionId': typeof ConnectConnectionIdRouteRouteWithChildren
  '/connections/new': typeof ConnectionsNewRoute
  '/connections/$connectionId/edit': typeof ConnectionsConnectionIdEditRoute
  '/connect/$connectionId/': typeof ConnectConnectionIdIndexRoute
  '/connect/$connectionId/$database/$schema/$table/structure': typeof ConnectConnectionIdDatabaseSchemaTableStructureRoute
  '/connect/$connectionId/$database/$schema/$table/': typeof ConnectConnectionIdDatabaseSchemaTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect/$connectionId'
    | '/connections/new'
    | '/connections/$connectionId/edit'
    | '/connect/$connectionId/'
    | '/connect/$connectionId/$database/$schema/$table/structure'
    | '/connect/$connectionId/$database/$schema/$table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections/new'
    | '/connections/$connectionId/edit'
    | '/connect/$connectionId'
    | '/connect/$connectionId/$database/$schema/$table/structure'
    | '/connect/$connectionId/$database/$schema/$table'
  id:
    | '__root__'
    | '/'
    | '/connect/$connectionId'
    | '/connections/new'
    | '/connections/$connectionId/edit'
    | '/connect/$connectionId/'
    | '/connect/$connectionId/$database/$schema/$table/structure'
    | '/connect/$connectionId/$database/$schema/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectConnectionIdRouteRoute: typeof ConnectConnectionIdRouteRouteWithChildren
  ConnectionsNewRoute: typeof ConnectionsNewRoute
  ConnectionsConnectionIdEditRoute: typeof ConnectionsConnectionIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/new': {
      id: '/connections/new'
      path: '/connections/new'
      fullPath: '/connections/new'
      preLoaderRoute: typeof ConnectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$connectionId': {
      id: '/connect/$connectionId'
      path: '/connect/$connectionId'
      fullPath: '/connect/$connectionId'
      preLoaderRoute: typeof ConnectConnectionIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$connectionId/': {
      id: '/connect/$connectionId/'
      path: '/'
      fullPath: '/connect/$connectionId/'
      preLoaderRoute: typeof ConnectConnectionIdIndexRouteImport
      parentRoute: typeof ConnectConnectionIdRouteRoute
    }
    '/connections/$connectionId/edit': {
      id: '/connections/$connectionId/edit'
      path: '/connections/$connectionId/edit'
      fullPath: '/connections/$connectionId/edit'
      preLoaderRoute: typeof ConnectionsConnectionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$connectionId/$database/$schema/$table/': {
      id: '/connect/$connectionId/$database/$schema/$table/'
      path: '/$database/$schema/$table'
      fullPath: '/connect/$connectionId/$database/$schema/$table/'
      preLoaderRoute: typeof ConnectConnectionIdDatabaseSchemaTableIndexRouteImport
      parentRoute: typeof ConnectConnectionIdRouteRoute
    }
    '/connect/$connectionId/$database/$schema/$table/structure': {
      id: '/connect/$connectionId/$database/$schema/$table/structure'
      path: '/$database/$schema/$table/structure'
      fullPath: '/connect/$connectionId/$database/$schema/$table/structure'
      preLoaderRoute: typeof ConnectConnectionIdDatabaseSchemaTableStructureRouteImport
      parentRoute: typeof ConnectConnectionIdRouteRoute
    }
  }
}

interface ConnectConnectionIdRouteRouteChildren {
  ConnectConnectionIdIndexRoute: typeof ConnectConnectionIdIndexRoute
  ConnectConnectionIdDatabaseSchemaTableStructureRoute: typeof ConnectConnectionIdDatabaseSchemaTableStructureRoute
  ConnectConnectionIdDatabaseSchemaTableIndexRoute: typeof ConnectConnectionIdDatabaseSchemaTableIndexRoute
}

const ConnectConnectionIdRouteRouteChildren: ConnectConnectionIdRouteRouteChildren =
  {
    ConnectConnectionIdIndexRoute: ConnectConnectionIdIndexRoute,
    ConnectConnectionIdDatabaseSchemaTableStructureRoute:
      ConnectConnectionIdDatabaseSchemaTableStructureRoute,
    ConnectConnectionIdDatabaseSchemaTableIndexRoute:
      ConnectConnectionIdDatabaseSchemaTableIndexRoute,
  }

const ConnectConnectionIdRouteRouteWithChildren =
  ConnectConnectionIdRouteRoute._addFileChildren(
    ConnectConnectionIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectConnectionIdRouteRoute: ConnectConnectionIdRouteRouteWithChildren,
  ConnectionsNewRoute: ConnectionsNewRoute,
  ConnectionsConnectionIdEditRoute: ConnectionsConnectionIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
