/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectionsNewRouteImport } from './routes/_app/connections/new'
import { Route as AppConnectConnectionIdRouteRouteImport } from './routes/_app/connect/$connectionId/route'
import { Route as AppConnectConnectionIdIndexRouteImport } from './routes/_app/connect/$connectionId/index'
import { Route as AppConnectionsConnectionIdEditRouteImport } from './routes/_app/connections/$connectionId/edit'
import { Route as AppConnectConnectionIdUsersRouteImport } from './routes/_app/connect/$connectionId/users'
import { Route as AppConnectConnectionIdImportRouteImport } from './routes/_app/connect/$connectionId/import'
import { Route as AppConnectConnectionIdDumpsRouteImport } from './routes/_app/connect/$connectionId/dumps'
import { Route as AppConnectConnectionIdDatabasesRouteImport } from './routes/_app/connect/$connectionId/databases'
import { Route as AppConnectConnectionIdDatabaseSchemaTableIndexRouteImport } from './routes/_app/connect/$connectionId/$database/$schema/$table/index'
import { Route as AppConnectConnectionIdDatabaseSchemaTableStructureRouteImport } from './routes/_app/connect/$connectionId/$database/$schema/$table/structure'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConnectionsNewRoute = AppConnectionsNewRouteImport.update({
  id: '/connections/new',
  path: '/connections/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConnectConnectionIdRouteRoute =
  AppConnectConnectionIdRouteRouteImport.update({
    id: '/connect/$connectionId',
    path: '/connect/$connectionId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConnectConnectionIdIndexRoute =
  AppConnectConnectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)
const AppConnectionsConnectionIdEditRoute =
  AppConnectionsConnectionIdEditRouteImport.update({
    id: '/connections/$connectionId/edit',
    path: '/connections/$connectionId/edit',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConnectConnectionIdUsersRoute =
  AppConnectConnectionIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)
const AppConnectConnectionIdImportRoute =
  AppConnectConnectionIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)
const AppConnectConnectionIdDumpsRoute =
  AppConnectConnectionIdDumpsRouteImport.update({
    id: '/dumps',
    path: '/dumps',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)
const AppConnectConnectionIdDatabasesRoute =
  AppConnectConnectionIdDatabasesRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)
const AppConnectConnectionIdDatabaseSchemaTableIndexRoute =
  AppConnectConnectionIdDatabaseSchemaTableIndexRouteImport.update({
    id: '/$database/$schema/$table/',
    path: '/$database/$schema/$table/',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)
const AppConnectConnectionIdDatabaseSchemaTableStructureRoute =
  AppConnectConnectionIdDatabaseSchemaTableStructureRouteImport.update({
    id: '/$database/$schema/$table/structure',
    path: '/$database/$schema/$table/structure',
    getParentRoute: () => AppConnectConnectionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/connect/$connectionId': typeof AppConnectConnectionIdRouteRouteWithChildren
  '/connections/new': typeof AppConnectionsNewRoute
  '/connect/$connectionId/databases': typeof AppConnectConnectionIdDatabasesRoute
  '/connect/$connectionId/dumps': typeof AppConnectConnectionIdDumpsRoute
  '/connect/$connectionId/import': typeof AppConnectConnectionIdImportRoute
  '/connect/$connectionId/users': typeof AppConnectConnectionIdUsersRoute
  '/connections/$connectionId/edit': typeof AppConnectionsConnectionIdEditRoute
  '/connect/$connectionId/': typeof AppConnectConnectionIdIndexRoute
  '/connect/$connectionId/$database/$schema/$table/structure': typeof AppConnectConnectionIdDatabaseSchemaTableStructureRoute
  '/connect/$connectionId/$database/$schema/$table/': typeof AppConnectConnectionIdDatabaseSchemaTableIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/connections/new': typeof AppConnectionsNewRoute
  '/connect/$connectionId/databases': typeof AppConnectConnectionIdDatabasesRoute
  '/connect/$connectionId/dumps': typeof AppConnectConnectionIdDumpsRoute
  '/connect/$connectionId/import': typeof AppConnectConnectionIdImportRoute
  '/connect/$connectionId/users': typeof AppConnectConnectionIdUsersRoute
  '/connections/$connectionId/edit': typeof AppConnectionsConnectionIdEditRoute
  '/connect/$connectionId': typeof AppConnectConnectionIdIndexRoute
  '/connect/$connectionId/$database/$schema/$table/structure': typeof AppConnectConnectionIdDatabaseSchemaTableStructureRoute
  '/connect/$connectionId/$database/$schema/$table': typeof AppConnectConnectionIdDatabaseSchemaTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/connect/$connectionId': typeof AppConnectConnectionIdRouteRouteWithChildren
  '/_app/connections/new': typeof AppConnectionsNewRoute
  '/_app/connect/$connectionId/databases': typeof AppConnectConnectionIdDatabasesRoute
  '/_app/connect/$connectionId/dumps': typeof AppConnectConnectionIdDumpsRoute
  '/_app/connect/$connectionId/import': typeof AppConnectConnectionIdImportRoute
  '/_app/connect/$connectionId/users': typeof AppConnectConnectionIdUsersRoute
  '/_app/connections/$connectionId/edit': typeof AppConnectionsConnectionIdEditRoute
  '/_app/connect/$connectionId/': typeof AppConnectConnectionIdIndexRoute
  '/_app/connect/$connectionId/$database/$schema/$table/structure': typeof AppConnectConnectionIdDatabaseSchemaTableStructureRoute
  '/_app/connect/$connectionId/$database/$schema/$table/': typeof AppConnectConnectionIdDatabaseSchemaTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connect/$connectionId'
    | '/connections/new'
    | '/connect/$connectionId/databases'
    | '/connect/$connectionId/dumps'
    | '/connect/$connectionId/import'
    | '/connect/$connectionId/users'
    | '/connections/$connectionId/edit'
    | '/connect/$connectionId/'
    | '/connect/$connectionId/$database/$schema/$table/structure'
    | '/connect/$connectionId/$database/$schema/$table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/connections/new'
    | '/connect/$connectionId/databases'
    | '/connect/$connectionId/dumps'
    | '/connect/$connectionId/import'
    | '/connect/$connectionId/users'
    | '/connections/$connectionId/edit'
    | '/connect/$connectionId'
    | '/connect/$connectionId/$database/$schema/$table/structure'
    | '/connect/$connectionId/$database/$schema/$table'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/connect/$connectionId'
    | '/_app/connections/new'
    | '/_app/connect/$connectionId/databases'
    | '/_app/connect/$connectionId/dumps'
    | '/_app/connect/$connectionId/import'
    | '/_app/connect/$connectionId/users'
    | '/_app/connections/$connectionId/edit'
    | '/_app/connect/$connectionId/'
    | '/_app/connect/$connectionId/$database/$schema/$table/structure'
    | '/_app/connect/$connectionId/$database/$schema/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connections/new': {
      id: '/_app/connections/new'
      path: '/connections/new'
      fullPath: '/connections/new'
      preLoaderRoute: typeof AppConnectionsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connect/$connectionId': {
      id: '/_app/connect/$connectionId'
      path: '/connect/$connectionId'
      fullPath: '/connect/$connectionId'
      preLoaderRoute: typeof AppConnectConnectionIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connect/$connectionId/': {
      id: '/_app/connect/$connectionId/'
      path: '/'
      fullPath: '/connect/$connectionId/'
      preLoaderRoute: typeof AppConnectConnectionIdIndexRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
    '/_app/connections/$connectionId/edit': {
      id: '/_app/connections/$connectionId/edit'
      path: '/connections/$connectionId/edit'
      fullPath: '/connections/$connectionId/edit'
      preLoaderRoute: typeof AppConnectionsConnectionIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connect/$connectionId/users': {
      id: '/_app/connect/$connectionId/users'
      path: '/users'
      fullPath: '/connect/$connectionId/users'
      preLoaderRoute: typeof AppConnectConnectionIdUsersRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
    '/_app/connect/$connectionId/import': {
      id: '/_app/connect/$connectionId/import'
      path: '/import'
      fullPath: '/connect/$connectionId/import'
      preLoaderRoute: typeof AppConnectConnectionIdImportRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
    '/_app/connect/$connectionId/dumps': {
      id: '/_app/connect/$connectionId/dumps'
      path: '/dumps'
      fullPath: '/connect/$connectionId/dumps'
      preLoaderRoute: typeof AppConnectConnectionIdDumpsRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
    '/_app/connect/$connectionId/databases': {
      id: '/_app/connect/$connectionId/databases'
      path: '/databases'
      fullPath: '/connect/$connectionId/databases'
      preLoaderRoute: typeof AppConnectConnectionIdDatabasesRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
    '/_app/connect/$connectionId/$database/$schema/$table/': {
      id: '/_app/connect/$connectionId/$database/$schema/$table/'
      path: '/$database/$schema/$table'
      fullPath: '/connect/$connectionId/$database/$schema/$table/'
      preLoaderRoute: typeof AppConnectConnectionIdDatabaseSchemaTableIndexRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
    '/_app/connect/$connectionId/$database/$schema/$table/structure': {
      id: '/_app/connect/$connectionId/$database/$schema/$table/structure'
      path: '/$database/$schema/$table/structure'
      fullPath: '/connect/$connectionId/$database/$schema/$table/structure'
      preLoaderRoute: typeof AppConnectConnectionIdDatabaseSchemaTableStructureRouteImport
      parentRoute: typeof AppConnectConnectionIdRouteRoute
    }
  }
}

interface AppConnectConnectionIdRouteRouteChildren {
  AppConnectConnectionIdDatabasesRoute: typeof AppConnectConnectionIdDatabasesRoute
  AppConnectConnectionIdDumpsRoute: typeof AppConnectConnectionIdDumpsRoute
  AppConnectConnectionIdImportRoute: typeof AppConnectConnectionIdImportRoute
  AppConnectConnectionIdUsersRoute: typeof AppConnectConnectionIdUsersRoute
  AppConnectConnectionIdIndexRoute: typeof AppConnectConnectionIdIndexRoute
  AppConnectConnectionIdDatabaseSchemaTableStructureRoute: typeof AppConnectConnectionIdDatabaseSchemaTableStructureRoute
  AppConnectConnectionIdDatabaseSchemaTableIndexRoute: typeof AppConnectConnectionIdDatabaseSchemaTableIndexRoute
}

const AppConnectConnectionIdRouteRouteChildren: AppConnectConnectionIdRouteRouteChildren =
  {
    AppConnectConnectionIdDatabasesRoute: AppConnectConnectionIdDatabasesRoute,
    AppConnectConnectionIdDumpsRoute: AppConnectConnectionIdDumpsRoute,
    AppConnectConnectionIdImportRoute: AppConnectConnectionIdImportRoute,
    AppConnectConnectionIdUsersRoute: AppConnectConnectionIdUsersRoute,
    AppConnectConnectionIdIndexRoute: AppConnectConnectionIdIndexRoute,
    AppConnectConnectionIdDatabaseSchemaTableStructureRoute:
      AppConnectConnectionIdDatabaseSchemaTableStructureRoute,
    AppConnectConnectionIdDatabaseSchemaTableIndexRoute:
      AppConnectConnectionIdDatabaseSchemaTableIndexRoute,
  }

const AppConnectConnectionIdRouteRouteWithChildren =
  AppConnectConnectionIdRouteRoute._addFileChildren(
    AppConnectConnectionIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppConnectConnectionIdRouteRoute: typeof AppConnectConnectionIdRouteRouteWithChildren
  AppConnectionsNewRoute: typeof AppConnectionsNewRoute
  AppConnectionsConnectionIdEditRoute: typeof AppConnectionsConnectionIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppConnectConnectionIdRouteRoute:
    AppConnectConnectionIdRouteRouteWithChildren,
  AppConnectionsNewRoute: AppConnectionsNewRoute,
  AppConnectionsConnectionIdEditRoute: AppConnectionsConnectionIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
